### ISSUE TITLE
API问题

### ISSUE THREAD

**Issue by e790a8** [zxcm1/xmyd#1]
大佬，你咋抓到步数那个api的呀？？
用的什么抓包工具？

**Comment by SVHAPI** [comment]
我用的苹果端的Strea‪m
软件：https://apps.apple.com/cn/app/stream/id1312141691




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zxcm1/xmyd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月3日(星期六) 下午4:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zxcm1/xmyd] API问题 (#1)





 
大佬，你咋抓到步数那个api的呀？？
 用的什么抓包工具？

**Comment by e790a8** [comment]
> 我用的苹果端的Strea‪m 软件：https://apps.apple.com/cn/app/stream/id1312141691
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zxcm1/xmyd" ***@***.***&gt;; 发送时间:&nbsp;2021年4月3日(星期六) 下午4:04 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[zxcm1/xmyd] API问题 (#1) 大佬，你咋抓到步数那个api的呀？？ 用的什么抓包工具？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
哦，我是安卓，用的httpcanary

**Comment by SVHAPI** [comment]
主要是分析数据包里的内容
